### ISSUE TITLE
CSLItemDataBuilder should have page(String, String) method

### ISSUE THREAD

**Issue by Possommi** [michel-kraemer/citeproc-java#232]
With the new 3.0 version ```CSLItemDataBuilder#pageFirst()``` and ```CSLItemDataBuilder#pageLast()``` have been removed and replaced by ```page(int, int)```. Through this it is now not possible to express start/end with roman numbers.

**Which version of citeproc-java are you using?**
3.0

**Comment by michel-kraemer** [comment]
Please note that a `pageLast` method has never existed (at least not that I'm aware of). The correct way was always to use `page(String)` and pass it something like `1–10` or in your case `I–IV`. The method automatically parses the page range.

The `pageFirst()` method has been removed because the `page-first` variable is actually a synthetic variable dynamically generated from the `page` variable during CSL processing. It should not be exposed to the outside and should not be available through the item data builder.

Nevertheless, I see your point that the API is misleading at the moment. I will add a `page(String, String)` method in addition to the `page(String)` and the `page(int, int)` method. Please not, however, that this method will do just the same as `page(int, int)`, namely creating a page range and passing it to `page(String)`, which you can already do right now (as described above).

For reference, see the implementation of the `page(int, int)` method here:
https://github.com/michel-kraemer/citeproc-java/blob/138f22aa4e579a8b6e5af6698ee7ef37d4092f41/citeproc-java/templates/CSLItemData.json#L358

**Comment by michel-kraemer** [comment]
Thanks for the feature request. The new method is available now in version 3.1.0.
