### ISSUE TITLE
Event output is missing in citations

### ISSUE THREAD

**Issue by kkrebs** [michel-kraemer/citeproc-java#238]
**Describe the bug**
After updating to current citeproc-java version the event information is missing.
Before update:
Arning, Ursula (2022): PUBLISSO – Publishing open access for achieving the Sustainable Development Goals (SDGS). In: 87th IFLA World Library and Information Congress (WLIC) / 2022, Dublin, Ireland, 26.07.-29.07.2022. Online verfügbar unter: https://repository. ifla.org/handle/123456789/2312.

After update:
Arning, Ursula (2022): PUBLISSO – Publishing open access for achieving the Sustainable Development Goals (SDGS). In. Online verfügbar unter: https://repository.ifla.org/handle/123456789/2312.

**Which version of citeproc-java are you using?**
3.0.0

**Expected behavior**
see event information in citation

**Actual behavior**
Output of event information is missing. Should be:
"In: 87th IFLA World Library and Information Congress (WLIC) / 2022, Dublin, Ireland, 26.07.-29.07.2022."

**CSL input**
```
[
  {
    "id": "bibthk_mods_00010225",
    "type": "article",
    "language": "en",
    "author": [
      {
        "family": "Arning",
        "given": "Ursula",
        "isInstitution": false
      }
    ],
    "issued": {
      "raw": "2022-11-15"
    },
    "event": "87th IFLA World Library and Information Congress (WLIC); Dublin, Ireland; 26.07.-29.07.2022",
    "title": "PUBLISSO – Publishing open access for achieving the Sustainable Development Goals (SDGS)",
    "title-short": "PUBLISSO – Publishing open access for achieving the Sustainable Development Goals (SDGS)",
    "URL": "https://repository.ifla.org/handle/123456789/2312"
  }
]
```

**Used style and locale**
https://github.com/gbv/ubo_koeln/blob/master/src/main/resources/th-koeln.csl

**Comment by michel-kraemer** [comment]
I've had a look at the style file and noticed that it tries to access the `event` variable through the `<cs:names>` element in lines 250-255:

```xml
<text term="in" text-case="capitalize-first"/>
<group delimiter=": " suffix=".">
<names variable="event">
<label form="short" prefix=" (" suffix=")"/>
</names>
</group>
```

The [CSL specification](https://docs.citationstyles.org/en/stable/index.html) states that *“The `cs:names` rendering element outputs the contents of one or more name variables”* (see section [Names](https://docs.citationstyles.org/en/stable/specification.html#names)). `event` is not a name variable. Valid name variables are `author`, `editor`, or `translator`, for example (see the [list of name variables](https://docs.citationstyles.org/en/stable/specification.html#name-variables) from the specification).

To make this work, you have to replace the `cs:names` element with a `cs:text` element like so:

```xml
<text term="in" text-case="capitalize-first"/>
<group delimiter=": " suffix=".">
<text variable="event" />
</group>
```

After doing so, citeproc-java produces the expected output:

> Arning, Ursula (2022): PUBLISSO – Publishing open access for achieving the Sustainable Development Goals (SDGS). In: 87th IFLA World Library and Information Congress (WLIC); Dublin, Ireland; 26.07.-29.07.2022. Online verfügbar unter: https://repository.ifla.org/handle/123456789/2312

Note that I've also removed the `label` child element to make the XML valid. This element normally renders the label of the name variable (e.g. `Editor`, `Translator`). Since `event` is not a name variable, it did not render anything, so it can be safely removed.

**Comment by kkrebs** [comment]
thanks for helping! I tested it with https://editor.citationstyles.org/visualEditor/ but this seems to be less restrictive
