### ISSUE TITLE
Problem with italic text (\texit) in bibtex entry

### ISSUE THREAD

**Issue by Siedlerchr** [michel-kraemer/citeproc-java#84]
Our JabRef internal Preview renders it correctly in italic.
Hower, using the IEEE or any other style I see the Unicode replacement symbols
![grafik](https://user-images.githubusercontent.com/320228/75522966-70184400-5a0b-11ea-8576-ee59acb535ed.png)

```
@Article{,
  author = {Test},
  title  = {New information on \textit{Riograndia guaibensis} Bonaparte,},
}
```
CSL style is IEEE
 2.1.0-SNAPSHOT (from two days ago)

**Comment by Siedlerchr** [comment]
Maybe related, I experience the same using math characters
` $\mathcal{H}$`

**Comment by michel-kraemer** [comment]
@Siedlerchr Thanks for reporting this. However, I cannot reproduce it. I used the following code:

```java
String entry = "@Article{,\n" +
        "  author = {Test},\n" +
        "  title  = {New information on \\textit{Riograndia guaibensis} Bonaparte,},\n" +
        "}";

ByteArrayInputStream bais = new ByteArrayInputStream(
        entry.getBytes(StandardCharsets.UTF_8));

BibTeXDatabase db = new BibTeXConverter().loadDatabase(bais);
BibTeXItemDataProvider sys = new BibTeXItemDataProvider();
sys.addDatabase(db);

try (CSL citeproc = new CSL(sys, "ieee")) {
    citeproc.setOutputFormat("html");
    sys.registerCitationItems(citeproc);

    Bibliography bibl = citeproc.makeBibliography();
    for (String e : bibl.getEntries()) {
        assertEquals("<div class=\"csl-entry\">\n" +
                "    <div class=\"csl-left-margin\">[1]</div>" +
                "<div class=\"csl-right-inline\">Test, " +
                "“New information on Riograndia guaibensis Bonaparte,.”</div>\n" +
                "  </div>", e.trim());
    }
}
```

Regardless of which mode I use (the old JavaScript processor or the new pure Java implementation), I get the same result without any unicode characters or LaTeX statements. I think this is to be expected as this code here removes all LaTeX statements: https://github.com/michel-kraemer/citeproc-java/blob/master/citeproc-java/src/main/java/de/undercouch/citeproc/bibtex/BibTeXConverter.java#L167-L172

I suspect an encoding issue. Can you change the code above so that I can reproduce the problem? Thanks.
