### ISSUE TITLE
APA style is taking significantly longer time to return the citation

### ISSUE THREAD

**Issue by PrimoQA** [michel-kraemer/citeproc-java#95]
Hello Michel, thank you for your help.
We are using different styles in our service, and we've noticed that the APA style is taking significantly longer time to return the citation.
Is this issue familiar to you? is it depends on the environment or the csl file?

Thanks

**Comment by michel-kraemer** [comment]
Which version of citeproc-java do you use?

**Comment by PrimoQA** [comment]
Those are the dependencies we're using:
org.citationstyles
styles
20.11-SNAPSHOT
...
org.citationstyles
locales
20.11-SNAPSHOT
...
de.undercouch
citeproc-java
2.0.0

**Comment by gallardo** [comment]
For the record, I have benchmarked the rendering time of bibliographies using a few of the styles in citationstyles, and APA requires the longest processing time.

For comparison, very roughly, the rendering of 200 Items took:

- with APA: 1320 ms
- with Chicago: 1100 ms
- with Din-1505-2: 715 ms
- with Harvard: 705 ms
- with IEEE: 315 ms
- with Springer: 205 ms
- with Vancouver: 305 ms

Even the creation of the processor (`new CSL(..., style)`) is remarkably expensive in APA, taking 10 to 20 times more time than wit simpler styles.

This makes sense if you analyse the complexity of the styles. I don't think that this caused by citeproc-java.

**Comment by michel-kraemer** [comment]
@PrimoQA @gallardo Thanks for the information and the benchmark. Can you try again with the latest alpha version I've just released (3.0.0-alpha.1). This version should be significantly faster.
